/**
 * Centralized Error Types
 * All application errors are categorized here
 */

export enum ErrorType {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',
  AUTH_INVALID_EMAIL = 'AUTH_INVALID_EMAIL',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  
  // Network Errors
  NETWORK_ERROR = 'NETWORK_ERROR',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  NETWORK_OFFLINE = 'NETWORK_OFFLINE',
  
  // Server Errors
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE',
  SERVER_MAINTENANCE = 'SERVER_MAINTENANCE',
  
  // Data Errors
  DATA_INVALID_RESPONSE = 'DATA_INVALID_RESPONSE',
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  DATA_VALIDATION_FAILED = 'DATA_VALIDATION_FAILED',
  
  // Subscription Errors
  SUBSCRIPTION_CREATE_FAILED = 'SUBSCRIPTION_CREATE_FAILED',
  SUBSCRIPTION_UPDATE_FAILED = 'SUBSCRIPTION_UPDATE_FAILED',
  SUBSCRIPTION_DELETE_FAILED = 'SUBSCRIPTION_DELETE_FAILED',
  SUBSCRIPTION_FETCH_FAILED = 'SUBSCRIPTION_FETCH_FAILED',
  
  // Profile Errors
  PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED',
  PROFILE_FETCH_FAILED = 'PROFILE_FETCH_FAILED',
  
  // Storage Errors
  STORAGE_ERROR = 'STORAGE_ERROR',
  
  // Form Validation Errors
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_EMAIL_FORMAT = 'VALIDATION_EMAIL_FORMAT',
  VALIDATION_PASSWORD_LENGTH = 'VALIDATION_PASSWORD_LENGTH',
  VALIDATION_PASSWORD_MISMATCH = 'VALIDATION_PASSWORD_MISMATCH',
  
  // Generic Errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export interface AppError {
  type: ErrorType;
  message: string;
  details?: string;
  technicalDetails?: any;
  retryable?: boolean;
  timestamp?: Date;
}

export interface ErrorAction {
  label: string;
  onPress: () => void;
}
